# Generated by Django 2.2.28 on 2023-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230523_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vinay',
        ),
        migrations.AddField(
            model_name='user',
            name='shubham',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
